[theme]
primaryColor = "#39FF14"
backgroundColor = "#0F0F23"
secondaryBackgroundColor = "#2D142C"
textColor = "#FFFFFF"
font = "monospace"

[server]
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
