[theme]
primaryColor = "#00FF00"          # Neon green for buttons and highlights
backgroundColor = "#000000"       # Black background
secondaryBackgroundColor = "#1A1A1A"  # Dark gray for secondary elements
textColor = "#FFFFFF"             # White text
font = "monospace"                # Base font (overridden by CSS for Orbitron)
